version: '3.7'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper
    container_name: zookeeper
    ports:
      - 2181:2181
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
    networks:
      - confluent

  kafka:
    image: confluentinc/cp-kafka
    container_name: kafka
    ports:
      - 9092:9092
    environment:
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_BROKER_ID=0
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_NUM_PARTITIONS=1
    networks:
      - confluent
    depends_on:
      - zookeeper

  kafka_1:
    image: confluentinc/cp-kafka
    container_name: kafka_1
    ports:
      - 9094:9094
    environment:
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka_1:9094
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_BROKER_ID=1
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_NUM_PARTITIONS=1
    networks:
      - confluent
    depends_on:
      - zookeeper

  twitter_producer:
    image: prass016/twitterkafkaproducer
    container_name: twitter_producer
    networks:
      - confluent
    depends_on:
      - zookeeper
      - kafka
      - kafka_1

  twitter_consumer:
    image: prass016/twitterkafkaconsumer
    container_name: twitter_consumer
    networks:
      - confluent
    depends_on:
      - zookeeper
      - kafka
      - kafka_1
      - twitter_producer

networks:
  confluent: 
    driver: bridge
